# Version bump labels
- name: "bump:major"
  color: "B60205"
  description: "Breaking changes that require a major version bump"

- name: "bump:minor"
  color: "FBCA04"
  description: "New features that require a minor version bump"

- name: "bump:patch"
  color: "0E8A16"
  description: "Bug fixes that require a patch version bump"

# Issue type labels
- name: "bug"
  color: "D73A4A"
  description: "Something isn't working"

- name: "feature"
  color: "0075CA"
  description: "New feature or request"

- name: "enhancement"
  color: "A2EEEF"
  description: "Improvement to existing features"

- name: "documentation"
  color: "0075CA"
  description: "Improvements or additions to documentation"

- name: "tests"
  color: "D4C5F9"
  description: "Test-related changes"

# Workflow labels
- name: "dependencies"
  color: "0366D6"
  description: "Pull requests that update a dependency file"

- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"