[tool.mypy]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = false
disallow_untyped_decorators = false
no_implicit_optional = false
strict_optional = false
warn_redundant_casts = true
warn_return_any = false
warn_unused_ignores = true
disallow_subclassing_any = false
warn_unused_configs = true
ignore_missing_imports = true